### ISSUE TITLE
Reverse homepage's 2 latest posts chronological order

### ISSUE THREAD

**Issue by amandavisconti** [achorg/ach.org#1]
The homepage is currently showing the two latest posts, but the older of the two first (March 8, then March 25). It would be nice to reverse this so the latest post is first.

I don't have Eleventy set up locally yet and have not developed with it yet, but looks like we may want to use `| reverse` piping, or something else discussed on [this thread](https://github.com/11ty/eleventy/issues/1046)?

**Comment by simonwiles** [comment]
Think that's on me, sorry!  Fix PR'd; let me know if you'd like me to merge it myself 👍️

Edit: actually, fwiw, I think it was broken here:

https://github.com/achorg/ach.org/commit/b4838bdf19bc00fac811ea4f0b7033ebf44eeff3#diff-1cc5571e716ec87a26ba820ac936a5531f60bd8c6b6f2e7225502b047cdb486eR15

**Comment by amandavisconti** [comment]
Merging would be great—thanks so much for investigating and fixing, @simonwiles !

**Comment by simonwiles** [comment]
I've merged the fix, but the site will need to be rebuilt and redeployed; it's not clear to me how that's currently being handled.  (In fact, the whole site seems to be down at present, but that looks like it's probably connected to Reclaim having another characteristic outage -- I'm unable to log in to the client area for another account -- rather than anything specific to ach.org).

![image](https://github.com/user-attachments/assets/30df32f8-9bd6-408a-8b8e-b3906290e16c)

**Comment by regan008** [comment]
@simonwiles Yes, they are down at the moment it seems. I have a deploy script that I've been using to rsync the site to the server. I have it set to be ignored by github so we don't accidentally make server credentials live. But I'm sure there is a more modern and elegant way to handle this. Any ideas? I am happy to switch to an easier system that can be shared across people.

**Comment by simonwiles** [comment]
There are lots of options, but since the source repo is here it could be done with a GitHub Action (either manually or automatically triggered) if you wanted.  The trick is to use a locked-down SSH key pair and keep the private key as a GitHub secret.  I've set something similar up several times -- including for the new (as-yet unlaunched) DHQ site.  A closely-related option would be to skip the Reclaim server altogether and host it on GH Pages (not sure if that would fit your needs exactly).  Happy to discuss and/or help with any of this, if it would be welcome.

**Comment by amandavisconti** [comment]
If it helps, Scholars' Lab hosts our website on GH Pages (recently moved from files on GH, but webhook sending to a university server to actually serve). It's for a Jekyll site (which has 2 options: GH Actions, or deploy from branch w/o Actions—the latter may not be available for Eleventy, not sure?). So far, it's been great as multiple folks can update, and the Actions dashboard has decent error messages if something happens meaning a deploy can't proceed.

**Comment by regan008** [comment]
Lets do the github action to deploy to our server then - that seems to make the most sense and its something I should know how to setup. I'd actually like to do the same for my own sites. @simonwiles, would you be able to help me set that up? I can generate an ssh key pairing if you need.
